using System;

namespace Action_Wheel.Services
{
    /// <summary>Identifies input generated by Action Wheel so its own hooks can ignore it.</summary>
    internal static class InputInjection
    {
        // Stable, process-independent marker. It is metadata only and never leaves the INPUT event.
        public static readonly IntPtr Marker = unchecked((IntPtr)(nint)0x4152494E); // "ARIN"
        public static readonly UIntPtr MouseMarker = unchecked((UIntPtr)(nuint)0x4152494E);
    }
}
